### ISSUE TITLE
Customers are loosing licenses when updating to Paddle 3.0.21 or higher

### ISSUE THREAD

**Issue by tunabelly** [PaddleHQ/Mac-Framework#141]
We just pushed an update for Folder Tidy and it includes Paddle 3.0.21. The old version had 2.4.3. 

One customer so far updated and it's now prompting him to re-enter his license key. In short, the Paddle framework did not convert his license to the v3 format. This is really not good since we went through this with TG Pro a while back and had 100s of support emails and angry customers.

If this happens again, it's going to be a support nightmare.

**Comment by avalore** [comment]
What version of the SDK did Folder Tidy use originally (the oldest version)?
Could you please email the customers licence details over?

**Comment by henderea** [comment]
Just wanted to say that I had the same issue when I updated folder tidy this morning.  I just looked up my license and put it back in, and it worked.  I've been a consumer-side user of paddle for quite a while, so I've been set up with my.paddle.com for a long time, and can just look stuff up there.  Not to say that you can expect very many of the customers to do that.

**Comment by Iomegan** [comment]
https://github.com/PaddleHQ/Mac-Framework/issues/131 might be related

**Comment by tunabelly** [comment]
@henderea thanks for letting me know about your experience. I had to send out an email blast to everyone who purchased Folder Tidy letting them know that they'll need to put their license key in again.

**Comment by tunabelly** [comment]
@Iomegan I checked out the other ticket (#131) and we're not doing the licensing silently so it may be a different issue.

**Comment by tunabelly** [comment]
So after issuing TG Pro 2.25 with the pre-release fix for #149, I now have multiple customers emailing saying that everything was working before and now it's lost their licenses. I got a really nice <sarcasm> email from a customer a few minutes ago:

> You did not adequately inform me that it would cost me $14 to use a product I already bought, now, I have reds all over the place, and no temperatures.
> 
> This iMac was $5,000 - if this thing fries as a result of your f-up, I’ll go after you with everything.
> 
> Get me?

So to be honest, fixing one bug is now causing another! This is lunacy.

**Comment by tunabelly** [comment]
Here's another one: 

> Im getting messages that i need go pay again. Thought i had already bought te full program. Please advise

This is getting very frustrating for both the paying customers and us.

**Comment by tunabelly** [comment]
I should clarify that this issue is now happening with the latest TG Pro update that includes the pre-release Paddle 3.0.25 (with the fix for #149).

**Comment by henderea** [comment]
Out of curiosity, would there actually be any legal grounds for suing for computer damage caused because an app wasn't doing anything?  I mean, I see why he would blame it on you for the software messing up, but can he really "go after you"?

Also, I would never say this to a customer, but customers that get *that* upset just because a piece of software has stopped working aren't really customers I want to deal with, especially when the software not working doesn't make things any *worse* than not having the software at all.  It isn't the software that's ruining his computer, the software just isn't *saving* it.  It isn't the fault of TG Pro that his computer runs so hot without it.

This situation is *somewhat* like taking an antidepressant and getting angry at the manufacturer when you still have symptoms.  No one promised that it would fix everything, but some people think that promise *has* been made.

Personally, I prefer to avoid working on software that gets too far into messing with the system.  This is mainly because I don't want to open myself up to the possibility of people blaming me for their computer being ruined.  Those apps still should be made, but as a solo hobby developer, I'd rather not be the one to get mixed up in that stuff.  If I actually made a living off of my app development, I might consider it, but as it is, I don't even make enough from my app to cover the costs of the services I use with it, so it isn't really a source of income for me and I don't want to spend much time on support if I can avoid it.

**Comment by tunabelly** [comment]
@henderea I believe you're right that he can't go after Tunabelly if an app doesn't work. It's clearly stated in the EULA was rights customers have, and that's available on the TG Pro webpage, it's mentioned at the checkout and available in the app.

In the end, he apologized and he's actually a decent guy who was under a lot of stress. Then having a critical app (for him) loose the license and revert to "please purchase" after a simple update was too much.

**Comment by tunabelly** [comment]
@avalore @GregularExpressions this is getting maddening. I have customer after customer emailing me now complaining that the app has gone back to trial mode or worse, trial over after updating. Of course some understand that there are bugs in the Paddle SDK and some just blame us, since it's our app. 

I'm not sure what's going on with QA at Paddle but it's so bad now that I'm seriously considering switching to another service, or rolling out our own.

**Comment by henderea** [comment]
I thought I would mention that I personally use TG Pro, and the latest update works fine for me.  Not only did I not have the sparkle issue mentioned in the TG Pro release notes, but I also didn't have any issues with the licensing.

Personally, while I do feel that Paddle could do a better job with QA, I also understand that it is hard to find bugs that only happen to *some* people.  If it happened to everyone, I expect it would probably not make it to release.  I think the issues everyone has been seeing with the paddle framework are probably things that slipped through the cracks because they weren't tested on a machine with the config, installs, and other things that cause the case.  And because it's a framework and not an app of its own, their "users" are people who include it in their own apps, so they don't really have anyone to do beta testing. 

I can only really think of two ways Paddle could reduce the number and severity of bugs that make it out to the public.  First of all, they could increase their QA capacity, either by hiring more QA people or relying on an outside group for QA.  The second option would be to simplify their system and reduce the ways it can go wrong.  For example, they could simplify the storage of the license and trial info, and that would probably reduce the number of bugs a fair amount, but would also make it easier to cheat the system by resetting trials and stuff like that.

I've always understood paddle to be a relatively small team.  They might not be tiny, but they certainly don't seem to be "big".  There's a limit to what you can do with a small team.  When things work right, they have a pretty good system.  I chose them as a developer because I liked the experiences I had as a user with licensing apps that used paddle.  I personally think the look of the interface is pretty nice, and it's easy to use.  On top of that, integrating the paddle framework into an app is really easy.  The issue with Paddle is that when things go wrong, the company doesn't handle them as well as we would like.  I think part of that is the small team, but I do wonder how much of it might be due to poor organization and planning.

Anyway, I do agree that Paddle could do better at finding these issues themselves and at dealing with issues that come up.  However, I *do* understand that they can't catch everything, especially when a lot of the issues only happen to *some* end users.  Software that has no bugs or flaws might be a reality someday in the future, but that day likely won't come for quite a while.

BTW, if you're looking for an alternative licensing provider, [DevMate](https://devmate.com/) might be an option.  It has some integration with paddle, so that might make the transition easier.

**Comment by tunabelly** [comment]
@henderea I'm happy to hear you are enjoying TG Pro and that the update worked and you didn't get the "loose license" bug. It's not that I'm super upset because of one bug. I totally understand that apps have bugs (ours sometimes do too), except this at least the **3rd **time**** this type of bug that happened with TG Pro customers. Plus add in the occasional crashes, features not working (ex: remove invalid licenses, search broken in dashboard, etc) it's getting pretty frustrating.

Paddle has 25 employees (https://paddle.com/company) so it's not that small anymore. I've been with Paddle since almost the beginning of the Mac version and I've gone through all the growing pains. 

DevMate isn't really any option anymore for an alternative service since it was just purchased by Paddle.

I just want this bug fixed, especially since I reported it over a month ago, and it's tying up my time with customer support when I could be working on app updates, new features, etc.

**Comment by tunabelly** [comment]
Here's another example of how upset customers are getting since their registration is getting lost multiple times:

> I’m getting bloody sick and tired of your bull**** almost every time I have to update. GET IT RIGHT BEFORE ISSUING UPDATES TO YOUR PAYING CUSTOMERS
> 
> I just updated and it’s telling me to register. Well I’m having difficulty finding my my registration info.

**Comment by tunabelly** [comment]
Now I'm getting requests for refunds due to the inconvenience of this all:

> I already have the 2.25 and it still does it over and over.  Can I please get a refund for my $18.00? I cannot handle having to see the message about 10 days left in my trial period.  Great app if it worked.

**Comment by tunabelly** [comment]
Here's another example of the emails I'm getting:

> I have TG Pro bought a few yeas ago. After the upgrade (automatic) of the last Apple OS upgrade, I should pay US$ within 10 Days and if I check The TG Pro it looks as I would have a trial version. Is that a bad joke?

**Comment by GregularExpressions** [comment]
Hey @tunabelly 

I'm sorry to hear about your upset customers, I can appreciate how this would be quite frustrating for them and you.

There's been a number of compound issues that have resulted in you and your customers repeatedly experiencing this lost license behaviour and we agree that it's unacceptable and below the level of service and quality we aim to provide.

We're working on a solution to this particular problem that I'll discuss with you directly (Any one else experiencing this issue should also get in touch with us).

Thanks,
Greg.

**Comment by tjosten** [comment]
Hi,

@GregularExpressions please issue a clear statement whether it is currently safe to update to latest versions of the Paddle SDK or not. I have an update ready which includes the latest SDK which is currently on hold because of this thread. I am not willing to deal with any of the issues mentioned here, so I am awaiting your response shortly.

Thanks!

**Comment by GregularExpressions** [comment]
Hey @tjosten 

In general, yes the latest SDK version is safe (otherwise we'd have reverted) - the issue specifically stems from older (v2) builds of the SDK upgrading to newer (v3) builds. 

Do you know the spread of SDK versions in your user base? Happy to discuss the solution mentioned above with you directly if you believe you'll be impacted.

Thanks,
Greg.

**Comment by tjosten** [comment]
Hi @GregularExpressions, 

I'm quite sure the majority of my users is using builds which contain any 3.x version of the SDK, so I should be save.

Thanks!

**Comment by tunabelly** [comment]
@GregularExpressions thanks for the update on this. I'm replying to your personal email right now.

**Comment by tunabelly** [comment]
@GregularExpressions any update on the fix? I'm still getting a lot of angry customers who are pissed, and I mean pissed. This is really hurting both our paying customers and our brand. Very frustrating!!!

**Comment by GregularExpressions** [comment]
@tunabelly I'll email you today, we've implemented and tested the solution for normal licensing but we're having to make some adjustments to site licensing to prevent this same issue from manifesting there - we should have a build for you very soon.

**Comment by tunabelly** [comment]
@GregularExpressions I released a TG Pro update with the pre release version of the Paddle framework that you sent. Unfortunately, I just got an email from a customer where he lost his license:

> i updated TG Pro and its asking me for the license but i already purchased this a while ago ... i have to purchase it again?

**Comment by GregularExpressions** [comment]
@tunabelly Sorry to hear that, we're going to need to confirm as much as we can about this user as hopefully they're an edge case;

- Are we certain they updated to the version with the pre-release?
- Which version (of the framework) did they update from?
- Are they using site licensing?
- Can we get their .padl file?

**Comment by tunabelly** [comment]
@GregularExpressions I have another case where they definitely updated from an older version (Paddle 2.3.4) to the latest (Paddle 3.0.25 pre-release) and it's not working:

> I purchased a license for TG Pro 2.8.5 through MacUpdate in September 2015. Today I downloaded the update (TG Pro 2.2.6) but my license does not seem to be valid for this version.If the current one a paid upgrade?

**Comment by tunabelly** [comment]
@GregularExpressions to answer your questions directly, here are my best answers:

Q: Are we certain they updated to the version with the pre-release?
A: Yes, TG Pro 2.26 contains the latest pre-release framework you sent, along with the call to setShouldAutoVerify, which wouldn't have compiled with an older version.

Q: Which version (of the framework) did they update from?
A: One of them was from Paddle 2.3.4 for sure.

Q: Are they using site licensing?
A: For the customer who was using Paddle 2.3.4 , it wouldn't have been turned on, although it is on with Paddle 3.0.25.

Q: Can we get their .padl file?
A: I can try and ask them although is it useful even after they've re-entered their license key?

**Comment by GregularExpressions** [comment]
@tunabelly Thanks for the additional details, can you confirm when the pre-release build went live and the number of users you've had report a lost license since please? It's possible that these users had their license removed by a previous build already or as suggested previously are an edge case.

Does that seem feasible? (for the moment at least)

**Comment by tunabelly** [comment]
@GregularExpressions the pre-release version (TG Pro 2.26) went live on August 25th, 2017 around 9:30pm EST. So far we've had I believe 4 or 5 customers say their license has disappeared after updating to the latest version. I'm guessing there are many more who just don't email if they can find their license. It's usually the ones who can't find their license key that email us.

I don't believe they had it removed by a previous build since if they update now, they get the pre-release 3.0.15 framework. And at least one has confirmed that it happened when getting TG Pro 2.26, which has the pre-release version.

**Comment by GregularExpressions** [comment]
@tunabelly thanks for clarifying, we'll get back on this as a matter of urgency - I should have at least an update for you tomorrow (Thursday)

**Comment by GregularExpressions** [comment]
@tunabelly What do you think the likelihood is that users are running the app from ~/Downloads ?

**Comment by tjosten** [comment]
I am sorry for hijacking this issue, but I am continuously receiving reports like @tunabelly since a few days, where customers are being asked for their licensing information again after a restart of their Mac. This sounds like the exakt same symptoms that have been described in this thread.

I am currently shipping Paddle SDK 3.0.15 with the latest update of my app, and will update to the latest available SDK over the weekend. However, as the number of reports started rising out of nothing without me updating the app or SDK, I feel this might either be

- an issue with the licensing server-side or
- an issue with macOS 10.13? People are joining the public beta program increasingly

**Comment by GregularExpressions** [comment]
Hey @tjosten thanks for adding your experience to the issue, are these users updating from an older version or are you seeing this behaviour with new users on the latest version?

**Comment by tunabelly** [comment]
@GregularExpressions its possible some are running from the Downloads folder although not all. I'm also getting more angry customers since the last update was supposed to fix this. Here's an example of what I'm dealing with:

> There is a problem with my purchased copy of TG Pro, it operates only in trial mode, even AFTER installing the update that is supposed to fix this problem. Not happy about this!

**Comment by GregularExpressions** [comment]
@tunabelly It would be useful to get the padl file of a user who has their license lost on every launch/reboot if you could send it to us.

**Comment by tunabelly** [comment]
@GregularExpressions I've emailed you the customer's email so you can get whatever you need. I figured it would be easier if you dealt directly with him and get rid of the middle man.

**Comment by tjosten** [comment]
@GregularExpressions To my latest information, it happened suddenly to existing users without updating my app.

**Comment by tunabelly** [comment]
I don't know how much longer we can wait for a proper fix. We're getting customer so mad they want our app off their computer after using it for years. This is destroying our brand!!

**Comment by GregularExpressions** [comment]
Hey @tjosten do you have any example license keys or user emails that are experiencing this issue please?

You can email them to me: greg@paddle.com

Thanks,
Greg.

**Comment by GregularExpressions** [comment]
@tunabelly We believe we've found another circumstance where this can occur, if you could email me any license keys you know are still experiencing this issue that would be helpful in confirming.

**Comment by tunabelly** [comment]
I've sent a few emails of customers so hopefully that helps. We honestly can't wait any longer. We have customers believing our app is running some type of ransomware where we're forcing them to purchase it again. This bug has existed far too long - it needs to be fixed now!

**Comment by tunabelly** [comment]
@GregularExpressions I've just cc'ed you on a customer email where it's asking for the license key on every restart. I believe he's on the latest version. 

When can we expect a proper fix for this? It's really hurting our brand and reputation.
