### ISSUE TITLE
Paddle Customer Helpdesk <help@paddle.com> misbehaving

### ISSUE THREAD

**Issue by core-code** [PaddleHQ/Mac-Framework#143]
hello,

this is a bugreport about Paddle's helpdesk (help@paddle.com) misbehaving and being plain broken.

most of the time when customers can't find their license key e-mail or didn't even get this e-mail they contact me (the app developer) directly because they don't know that they should contact the Paddle customer helpdesk (help@paddle.com) instead. 

i usually reply to the customer that they can recover licenses by mailing the paddle helpdesk and also put <help@paddle.com> in CC so that they can directly solve the issue for the customer without the customer having to do anything additionally.

the problem is that the Paddle Customer Helpdesk employees seem to be completely clueless about how e-mailing works. they seem to ignore the fact that i am the developer of the app, not the customer. they either send the reply with the recovered license ONLY to me (instead of the customer) or they put the customer into CC. putting the customer into CC is bad, because this increases the likelyhood of the mail getting flagged as SPAM and rejected. of course they have to send the reply DIRECTLY to the customer, maybe putting me into CC. 

i've pointed out to <help@paddle.com> numerous times over the past 4 years that they should reply to the actual customer and not to me, but they don't seem to grasp the concept of e-mail and/or comunication in general.

here are some records of this happening over the past 4 years:
23. dec 2013	Phillip
20. feb 2014 	Simon		
17. mar 2014 	Simon		
25. mar 2014 	Simon		
28. may 2014 	Simon		
30. jul 2014 	Simon		
19. nov 2014	Simon
15. oct 2015	Michal
30. oct 2015 	Michal
30. mar 2015 	Simon
22. jul 2016	Simon
17. may 2017	Ahmed
24. jul 2017 	Michal

in all of these incidents the customer was either only put into CC or ignored at all and the response only sent to me.

furthermore there have been more incidents cause by a confused helpdesk, e.g. referring to me (the developer) in a case of a forgotten license key, when this is clearly a job for the paddle helpdesk to recover. 

some customers have expressed complete dissatisfaction with the paddle support helpdesk to me directly and told me they'll rather purchase on the Mac App Store. 

seriously, the (lack of) quality of the paddle helpdesk / customer support is the weakest point of 'Paddle' and makes me and my customers angry. please fix this.

**Comment by GregularExpressions** [comment]
Hi @core-code 

Thank you for sharing your experiences with us, I'm sorry to hear it hasn't met your expectations. I'll pass this onto the head of support for you.

The good news is that we're currently finalising (it's in beta with a few vendors) a User History \ License Recovery API. This'll facilitate a form on your side that the customer enters their email address into and is emailed their purchase history (including any license keys) with yourselves.

That should greatly reduce the need to interact with support to remedy lost license codes and generally offer a better experience to your customers.

I'll update this issue with links to the docs etc when the API goes public, which we currently expect to be within the next week or two.

Thanks,
Greg.

**Comment by OskarGroth** [comment]
I can only second your whole post. And I would add that the response time of Paddle support is way to slow. I have customers contacting me and questioning my business practices because I'm telling them to contact Paddle support, and when they do that they don't get a response from Paddle for over 2-3 days. Especially bad during weekends.

When a customer purchases a product for $20-$50 and makes a simple spelling mistake in their email, they expect better than being without money or product for several days.

**Comment by tunabelly** [comment]
I couldn't have read the last comment at a better time. I have a customer who's been charged for TG Pro ($18) and there is no transaction in the dashboard for them and of course they haven't received their license key yet. I've cc'ed Paddle support with my correspondence to him and my concern is that having to wait 2-3 days for a reply is too long. Especially for cases like this. So I'm probably going to have to generate a temporary license for him to use until this gets sorted out, which is not an ideal solution (and I can't be 100% certain that he has actually purchased it since I do get fake support requests).

Perhaps Paddle could have a option in our dashboards to file an emergency support request for cases where customers have paid and haven't gotten their licenses/receipts.

**Comment by adriangranados** [comment]
Pardon my ignorance, but how is that no transaction appears in the dashboard, even if the user entered an incorrect email? I've seen that only for cases where the transaction is flagged as possible fraud (if approved, the transaction will eventually appear).

**Comment by tunabelly** [comment]
I do have email alerts setup for transactions that get flagged so I'm aware of what's going on if the customer emails support. However in this case, the customer was charged and I'm unable to find any transaction that remotely resembles his email (I know sometimes it's a typo so a simple search won't always work).

A few months ago we had an issue with where Paddle got overwhelmed with customers and transactions weren't showing up for a few minutes to about an hour after purchasing. They were in a queue which was temporarily slowed down. So in this case, I have no idea what's going on which is why I've cc'ed Paddle support so they can get to bottom of this.

**Comment by adriangranados** [comment]
Ok, I didn't know you could setup those alerts. Make sense. I actually need to do that because lately I've received a few emails of users saying their transactions were denied using their CC. I know these users and they're legit. Never in the past had these issues, so I wonder if something has changed (these transactions are for higher amounts though).

**Comment by tunabelly** [comment]
It's on the dashboard under Vendor Settings -> Alerts.

**Comment by adriangranados** [comment]
Done. Thank you!

**Comment by involer** [comment]
Thanks for the feedback guys – we're going to look into the data around average response times, and weekends etc... and also make sure we're better tracking and understanding ticket accuracy.

If you have any specific examples feel free to forward to co@paddle.com so I can look into them directly and we can address.

Would be interested in your thoughts on dealing with erroneous email addresses/typos on the checkout and how we could better address these? Its something we're conscious of and have added typo suggestions on the checkout for common mistakes (gamil vs gmail etc...), but would be great to hear feedback.

**Comment by core-code** [comment]
thanks for looking into it. please don't forget about the issue that was most important to me according to the initial 'bug report'. not response time, although that is an issue as well. 

but the fact that the support replies to me (when i put them into CC when replying to a customer looking for his serial) - and sometimes ONLY to me - like i was the customer, instead of replying to the customer like it should obviously be done is a much more serious issue because its just plain wrong.

**Comment by OskarGroth** [comment]
@involer Sent you an email showcasing the issues here.

**Comment by core-code** [comment]
i'd like you to re-open this bug, since the problem is not improving, but actually getting worse.

today the paddle helpdesk referred a customer that was asking for recovery of a license to me, instead of helping the customer. 

its clearly the job of the paddle helpdesk to help customers recover their license. especially since paddle killed the locker.paddle.com service where this would have been possible for the customers to recover licenses themselves. that they are referring to me instead to do their work is unbelievable.

**Comment by GregularExpressions** [comment]
Hey @core-code 

Sorry to hear the customer's enquiry wasn't handled as you expected. I've spoken to order support about this and they'll be in contact with you shortly.

Greg.

**Comment by GregularExpressions** [comment]
hey @core-code we've identified the issue here, in some cases the buyer's email address was being added as the bcc (rather than the to) and you were being left as the to address. Which from your end would seem like you were the only recipient and is likely a little confusing from the buyer's end too. The thread with Dr. Eller is one such example of this.

We'll amend the support system / macros to prevent this in future.

**Comment by core-code** [comment]
thanks for improving this

**Comment by core-code** [comment]
well, i'd like this re-opened.


1.) i have just given up on forwarding e-mails to help@paddle.com . this should be the normal way to refer a customer to your helpdesk, as it saves the customer from having to send his request again. however, it is just impossible because your helpdesk does not seem to grasp what a forwarded e-mail is, and who the vendor and who the customer is. in fact, i have to reply to each customer in this way:

> can you contact help@paddle.com with this information? the company 'Paddle' handles everything related to purchase and activation of our product and they should be able to make sure that you get a refund.
> i'd forward your e-mail to them myself for your convenience, but they always get confused with forwarded e-mails so i think its better if you send it.


2.) we've experienced several cases over the past months, where the Paddle Helpdesk again has behaved in the worst possible way.

a.) we receive an e-mail with a customer having an activation/purchase/license option
b.) we defer this customer to help@paddle.com
c.) after a day or so, we get a e-mail from the Paddle helpdesk where they refer the very same customer back to us, telling them only the vendor can help with the issue

this is probably the **worse possible experience** the customer could have - he is deferred in circles. also, it makes us look incredibly stupid, when in fact your helpdesk has been incredibly stupid.

i am not sure what is going in with your helpdesk. when a customer clearly has an issue with activation/purchase/license, how on earth could they refer back to us? are they just too lazy to do their job and defer to us so they can go sleep instead? frankly its beyond me why this issue keeps re-appearing since we've joined Paddle. if there is one single thing you need to teach the helpdesk staff it is "don't refer to the vendor for Paddle issues". write it on the top of their monitors if need be.

just a few occurrences i found in my e-mail outlist -listing just initials for obvious privacy issues:

APV (Paddle) Sep 30, 19:00 BST
KAM (Paddle) Oct 9, 15:57 BST
JC (Paddle) Sep 4, 20:46 BST 
KB (Paddle) Jan 13, 09:09 GMT

let me be clear about this, if your helpdesk continues to make our customers angry and make us look stupid, we will just replace Paddle with Stripe. we can save a lot of time and frustration there.

**Comment by core-code** [comment]
this just happened again, and honestly i am fed up with your “helpdesk“ and their incompetence and reluctance to do their work.

a customer contacted us about changing the email address associated with his purchase.. this is obviously your job so i referred him to help@paddle.com
after letting the customer wait wait wait wait they just referred him back to us. WTF! how on earth can that happen? again?

i‘d like this and similar bug reports from @tunabelly re-opened as the issue is obviously not fixed  but worse than ever.

how can we interpret you silence on this matter? do you honestly think the support you are providing is acceptable? and just not responding to complaints makes the issue go away?

in any case, @JoMarques09 i await an official response on this
