### ISSUE TITLE
License keeps resetting between debugging sessions

### ISSUE THREAD

**Issue by lvandal** [PaddleHQ/Mac-Framework#163]
No matter how many times I call

`
defaults write my.bundle.id PaddleResetTrial -bool NO
`

and

`
defaults write my.bundle.id PaddleAccelerateTrial -bool NO
`

before *and* while debugging, the license is being reset every time. This is frustrating. How can I solve this?

**Comment by lvandal** [comment]
I'm using v3.0.25 by the way.

**Comment by pixeleyesltd** [comment]
I was about to start another Git issue myself! I found the opposite, I can't actually utilise the PaddleAccelerateTrial key at all, it simply doesn't accelerate my trial. It might be related.

I wonder if this is a defaults issue, as I test both my MAS and direct version on the same machine. I noticed both versions of the app, even though they have the same bundle ID, store different settings. When using the defaults command, it only reads and writes from the MAS app defaults. I haven't tested this (about to walk out the door), but perhaps specifying the app / plist path in defaults might work?

**Comment by GregularExpressions** [comment]
Hey @lvandal thanks for reporting this and thanks to @pixeleyesltd for your addition. We'll look into it, can you confirm Luc if your app is sandboxed and/or MAS please? Thanks,
Greg.

**Comment by lvandal** [comment]
Hi! The app is sandboxed but sold directly, not through the MAS.

**Comment by avalore** [comment]
@pixeleyesltd @lvandal If you have two apps sharing a bundle identifier then it depends which has registered the bundle identifier as to which one will be set when using the defaults command. There are two ways around this:

1) Set the values using `[[NSUserDefaults standardUserDefaults] setValue:[NSNumber numberWithBool:YES] forKey:@"PaddleAccelerateTrial"];` in your app before using the SDK (obviously being sure to remove this for production).
2) You can pass a path to the preferences file for an app directly to the `defaults` command rather than a bundle identifier. If Sandboxed this will be in `~/Library/Container/` or if not then in `~/Library/Preferences`. For example:
`defaults write ~/Library/Containers/bundle.id/Data/Library/Preferences/bundle.id PaddleAccelerateTrial -bool NO`

**Comment by lvandal** [comment]
None of the 2 solutions work for me.

**Comment by GregularExpressions** [comment]
Hey @lvandal we'll look into this some more.

**Comment by avalore** [comment]
@lvandal can you try just deleting the key `defaults delete my.bundle.id PaddleResetTrial`
We'll have a fix for this in the next release but in the meantime this should resolve it

**Comment by avalore** [comment]
@pixeleyesltd when you're trying this is your app being run from Xcode? Your app needs to be attached to a debugger for this to function

**Comment by lvandal** [comment]
Seems to solve the issue for now. Cheers!
