### ISSUE TITLE
Question about new "purge v2 licenses"

### ISSUE THREAD

**Issue by tunabelly** [PaddleHQ/Mac-Framework#178]
I'd like to implement this to cut down on piracy, especially with TG Pro although I have a serious concern. Our customers have gone though 3 or 4 times where the Paddle framework lost their license, it reverted to trial mode and they had to enter their licenses again. Never having this happen again is definitely a priority. 

I don't want to do anything that would cause this to happen again for paying customers. If we add this feature, I'm assuming some of them will have to enter their license key again? 

Also, is it the new `shouldRemoveAmbiguousLicenses` property to set for this? Or does it need to be used with the `shouldAutoVerify` property?

**Comment by GregularExpressions** [comment]
Hey @tunabelly 

> I don't want to do anything that would cause this to happen again for paying customers. If we add this feature, I'm assuming some of them will have to enter their license key again?

Yes, any user with a license issued during the v2 SDK's lifetime (which I believe we've seen some examples of in your customer base before) would have their activation destroyed and have to enter their license code in again - at which point it'll be activated along the >= v3.0 route and no-longer be ambiguous.

For any product launched with >= v3.0 of the SDK this represents an easy way to combat the keygens that abuse the v2.0 -> v3.0 upgrade path, unfortunately there's not an easy way to tell the difference between a keygen v2 license and a legitimate v2 license.

We've been discussing how to make this better for cases like yours, with legitimate v2 users, and at present our suggestion is:

- Add delegate method like 'willDestroyAmbiguousLicense:licenseKey`.
- In this delegate method the vendor could call `- (void)activateLicence:licenceCode email:email forChildProduct:childProductId withCompletionBlock:completionBlock` to silently trigger an activation attempt.
- If the license is a valid legacy license then it'll be silently activated, continue as is, and no-longer be ambiguous.
- If it fails to activate because we have no record of the license then it's likely keygen and deactivation is the correct path.

Does that sound like a potential solution from your perspective?

> Also, is it the new shouldRemoveAmbiguousLicenses property to set for this? Or does it need to be used with the shouldAutoVerify property?

Yes you're correct, they both need to be enabled. You can think of the `shouldRemoveAmbiguousLicenses` as a setting for `shouldAutoVerify`.

Let me know if you have any more questions.

Thanks,
Greg.

**Comment by tunabelly** [comment]
That's great info @GregularExpressions , thanks for the explanation. 

Before I implement this, I want to clarify if I follow the path that you've setup, will any v2 users with valid licenses have to re-enter their license key?

**Comment by tjosten** [comment]
@tunabelly Would you mind sharing if it worked well for you when you're done rolling it out?

**Comment by GregularExpressions** [comment]
Hey @tunabelly, thanks - that's no problem, you are welcome.

> I want to clarify if I follow the path that you've setup, will any v2 users with valid licenses have to re-enter their license key?

As it currently stands, yes they would. We'd need to implement the `willDestroyAmbiguousLicense:licenseKey` before it would be possible to avoid this - which we're prepared to do in the short term if you're happy with it as a solution?

@tjosten feel free to ask us if you'd like anything clarified.

**Comment by tunabelly** [comment]
@GregularExpressions thanks for the clarification. Yes, I would like to try what you're suggesting if Paddle is willing to implement the necessary functions. 

I can't have an update that causes customers to have to enter their license key again. It's already happened 4x with various Paddle framework updates and it's **really** bad when that happens.

**Comment by GregularExpressions** [comment]
@tunabelly we've done some additional research into this internally and come to the conclusion that we'll need to handle this natively in v4 of the mac SDKs.

The solution will be similar in nature to the approach we discussed, but we'll take some onus off of your implementation:

When we detect a license with no corresponding activation (something we're already doing and can be done locally) we will automatically attempt to activate it - solving the problem for any legitimately licensed users.

If the activation is denied then we'll call an optional delegate method along the lines of `-
 (bool) shouldDestroyAmbiguousLicense:licenseKey`. This will give yourself and other vendors the opportunity to decide what course of action should be taken, given that the most likely case at this point is piracy:

- Allow the license to be purged, de-activate the user.
- Try and up-sell the user at a discount.
- Prompt them to contact support.
- etc.

From our perspective it would be great to only do this work in the upcoming v4, how urgently were you looking to implement? v4 is approaching alpha state and will then likely need a month or two of testing and vendor feedback.

**Comment by tunabelly** [comment]
@GregularExpressions ok thanks for the update. To be honest this is something that I would have welcomed to have when the original feature to remove fake licenses was released. It sounds like I'll have to wait for v4 which is months off, so that's a bit disappointing.

I highly doubt Paddle would ok the resources to do a special build just for us and then redo the work for v4. We're probably one of the few vendors that has lots of customers with v2 licenses (we've been with Paddle almost since it launched).

**Comment by GregularExpressions** [comment]
@tunabelly yes, this is now a better solution - previously we were investigating and assessing the scale of the issue whilst still giving vendors a short term route forward on it.

As one of our most long standing, active, and communicative vendors using the SDK you're on my list for the beta phase of v4 - so you'll be a little ahead of the curve in terms of v4 release.

There are additional benefits to rolling this out in v3 also, given that the vast majority of piracy is happening through keygens masquerading as v2 licenses this would all but eliminate that in a flexible way. With that in mind, I expect we'll roll this out to v3 at some point, potentially while we're gathering v4 beta feedback.
