### ISSUE TITLE
Deactivate child product license is not correct

### ISSUE THREAD

**Issue by vicalloy** [PaddleHQ/Mac-Framework#186]
Paddle: v3.0.32
XCode: Version 9.2 (9C40b)
Swift: 4.0
macOS: 10.13.2 (17C88)

1. user `paddle.showActivateLicence(with: self.window, forChildProduct: xxx)` to show a child product license.
2. Click `Deactivate License`.
3. The product license deactivated not child product.

**Comment by GregularExpressions** [comment]
Hey @vicalloy 

Thanks for the report, we've identified the issue here.

The good news is that it is already fixed in the next major version (v4.0) which will be going into beta in the next few weeks, which I'd be happy to include you in.

How does that timeframe work for you? Is it more urgent from your side?

Thanks,
Greg.

**Comment by vicalloy** [comment]
I'm glad to join the beta plan.
We want to publish our App in the next month, and hope this bug can be fixed before the App published.

**Comment by GregularExpressions** [comment]
Hey @vicalloy glad to hear it, can you let me know your Paddle vendor ID please and I'll get you added to the list.

It's unlikely that v4.0 has gone to full release 1 month from now, we'll need to give our beta vendors some time to integrate and do a limited roll out. Is this issue a blocker for you launching?

Thanks,
Greg.

**Comment by GregularExpressions** [comment]
hey @vicalloy 

We're ready to start collecting feedback on the macOS SDK v4.0 beta, can you drop me an email on greg at paddle dot com please and I'll send it over.

Thanks,
Greg.
