### ISSUE TITLE
"image not found" from VST / AU audio plugin

### ISSUE THREAD

**Issue by adamski** [PaddleHQ/Mac-Framework#214]
I'm trying to use Paddle within a VST and AU audio plugin. 

I'm getting a crash with the following info:

> Library not loaded: @rpath/Paddle.framework/Versions/A/Paddle
>   Referenced from: ....
>   Reason: image not found

I've followed the instructions, and set Runpath Search Paths to `@executable_path/../Frameworks`.

I have Paddle working fine in a standalone app.

**Comment by GregularExpressions** [comment]
Hey @adamski 

This is probably due to Xcode config somehow (as I'm sure you've guessed). There are a few suggestions in this stack overflow [thread](https://stackoverflow.com/questions/24993752/os-x-framework-library-not-loaded-image-not-found) but I think it's probably subject to your environment as to which solutions might be applicable.

If you still don't have any luck can you send us screenshots of your Xcode config that mentions the framework please?

Thanks,
Greg.

**Comment by adamski** [comment]
So it looks like the correct setting is `@loader_path/../Frameworks`. It only seems to work from an archive build, I was testing via "Build for Profiling".

**Comment by GregularExpressions** [comment]
Thanks for letting us know @adamski!
