### ISSUE TITLE
Trial window + 10.11: app icon disappears

### ISSUE THREAD

**Issue by asciiz** [PaddleHQ/Mac-Framework#65]
OS X 10.11, Paddle SDK 2.3.5 
The app icon in the trial window disappears shortly after the window is displayed.
Works fine on OS X 10.10.

**Comment by involer** [comment]
This is probably due to Amazon S3 failing the ATS requirement in OS X 10.11 - adding an exception for the `amazonaws.com` domain should fix the issue. Although we are working with Amazon on a fix.

See details on adding the ATS bypass here:
http://mobile.awsblog.com/post/Tx2QM69ZE6BGTYX/Preparing-Your-Apps-for-iOS-9

**Comment by Omgitsu** [comment]
I'm seeing the same behavior on 10.11 latest SDK compiled on Xcode 7.1 targeting 10.10 *even with the ATS bypass.

Icon appears for a fraction of a second, then disappears.  Not sure what is going on in your code, but if it failed ATS wouldn't the icon just never show?

**Comment by involer** [comment]
The flash will be due to the app falling back to the local version of the icon specified in the dictionary before it gets an API response. Can you confirm that you're getting this even with the ATS exception for AWS? We are working on running these images on an alternate CDN until Amazon fixes their ATS/ SHA-2 issues.

The only issue we know of is that the S3/AWS certificates fail ATS, are you getting any warnings/ errors in the console/ debugger?

**Comment by Omgitsu** [comment]
```
NSURLSession/NSURLConnection HTTP load failed (kCFStreamErrorDomainSSL, -9802)
```

this is in my Info.plist

```
	<dict>
		<key>NSExceptionDomains</key>
		<dict>
			<key>amazonaws.com</key>
			<dict>
				<key>NSIncludesSubdomains</key>
				<true/>
				<key>NSThirdPartyExceptionMinimumTLSVersion</key>
				<string>TLSv1.0</string>
				<key>NSThirdPartyExceptionRequiresForwardSecrecy</key>
				<false/>
			</dict>
			<key>amazonaws.com.cn</key>
			<dict>
				<key>NSIncludesSubdomains</key>
				<true/>
				<key>NSThirdPartyExceptionMinimumTLSVersion</key>
				<string>TLSv1.0</string>
				<key>NSThirdPartyExceptionRequiresForwardSecrecy</key>
				<false/>
			</dict>
			<key>spreedly.com</key>
			<dict>
				<key>NSExceptionRequiresForwardSecrecy</key>
				<false/>
				<key>NSIncludesSubdomains</key>
				<true/>
			</dict>
		</dict>
	</dict>
```

reading the comments on the aws blog:
http://mobile.awsblog.com/post/Tx2QM69ZE6BGTYX/Preparing-Your-Apps-for-iOS-9
it seems that that fix doesn't work for everyone

and I'm not sure if there are differences between the workaround for iOS 9 and El-Capitan
