### ISSUE TITLE
Email address should be verified on checkout

### ISSUE THREAD

**Issue by tunabelly** [PaddleHQ/Mac-Framework#71]
When customers checkout they should have to verify their email address to ensure there are no typos.  I understand that it's easier to only have to type it once although I'm getting a lot of upset/angry/confused emails from the customers (avg I'd say 5-10 a week) asking where their license is since they already paid.

For signing up for services, I totally agree it should only be once since they can always do it again if there was a typo.  However in this case there is no second chance and they've already paid.

If this isn't the right solution, I'm totally open to something else as long as it cuts down on these support emails and the poor first experience for the customers.

**Comment by involer** [comment]
We've been working on some improvements here, some have rolled out in the background and we've seen a reduction in support due to it, here's what's happened so far:

* Email bounce tracking - we record bounce statuses of all email addresses, and flag them when an email is unsuccessful.
* Email blacklisting - emails that have previously bounced, or marked as spam are unable to checkout, user is prompted to use another email.

A lot of sellers we work with are against adding a second email field due to dropoff in conversion, however, I agree, it's important to have tradeoff between conversion and reducing customer support.

I'll create a ticket here to add email verification as a preference, so you can toggle it within your account, which will ask the user to enter their email twice on checkout. It'll be turned off by default, but I'll make a note to update this ticket when it's released (I estimate this will either be completed and deployed tomorrow, or deployed on Monday).

**Comment by involer** [comment]
I've just assigned this ticket to an engineer. We're working on it now.

**Comment by tunabelly** [comment]
That would be a fantastic choice to have - thanks for working on that.

Anything that improves the customer experience and cuts down on wasted support time (by both of us) is great news.

**Comment by bradjasper** [comment]
A common example I see of this is misspelled domain names like:

gmai.com
gmali.com
hotmai.com
hotmali.com
etc...

It might be easy to check for the most common 10 email domain names and see if they're really close to a known variant.

**Comment by tunabelly** [comment]
Any update on this?  

I'm really happy you guys were able to fix the license issue when on the same machine although this the second half that's taking up a large amount of my support time. Some days I'm getting more than one person with this and it's giving my brand a bad name because they are automatically assuming I did something wrong or I just took their money (to be honest I would probably think the same thing).

The good news is I'm able to look up their license key from the transactions page, although again it's eating up support time + the bad image thing.

Here's an example of a misspelt address:

-----lighitng1@gmail.com instead of -----lighting1@gmail.com

**Comment by involer** [comment]
(Clearing up Github) – Automatic typo fixing via suggestion was deployed in mid 2016. Email double-entry has been logged as a feature request.

**Comment by tunabelly** [comment]
Ok, although I still have customers who end up mistyping their email and get really angry when the license key doesn't come through. Some think it's a scam because of this. So I have to be very proactive to watch for these and look up their license manually and forward the two emails to them, then reply to the support ticket.

Having the email double entry would be one of the better ideas IMHO.

**Comment by involer** [comment]
@tunabelly Double entry is planned as a setting, but will be addressed by the web-team rather than SDK (hence closing of this ticket).

**Comment by tunabelly** [comment]
I totally agree this isn't the right place for it. How can we post tickets for the web-team?

**Comment by involer** [comment]
We're working on better external ticketing/issue reporting and external/public visibility into issues and their progress with the web and API teams. — I've passed along this specific issue, and will update when we have a more defined method of pushing tickets into the web/API workflow.
